name: Build pywho
on:
  push:
    branches:
      - main
    paths:
      - 'pywho.py'
  workflow_dispatch:

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  ubuntu-vm-build-job:
    name: Build for Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run venv, pip, build and git commit
        run: |
          python3 -m venv venv && . venv/bin/activate
          pip3 install --upgrade pip wheel setuptools
          pip3 install -r requirements.txt
          pip3 install pyinstaller sysv-ipc geoip2
          ./build.sh && mv -f *.tar.gz *.sha512sum bin
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git pull && git add bin && git commit -m "update ubuntu binary" && git push
      # - uses: actions/upload-artifact@v2
      #  with:
      #    name: artifact-build-ubuntu
      #    path: |
      #      *.tar.gz
      #      *.sha512sum
      #    if-no-files-found: error
 
  debian-container-build-job:
    name: Build for Debian
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - debian-release: buster
            python-version: 3.7
          - debian-release: bullseye
            python-version: 3.9
      fail-fast: false
    container: python:${{ matrix.python-version }}-${{ matrix.debian-release }}
    steps:
      - uses: actions/checkout@v2
      - name: Run apt, venv, pip, build and git commit
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update -y
          apt-get install -y upx-ucl
          python3 -m venv venv && . venv/bin/activate
          pip3 install --upgrade pip wheel setuptools
          pip3 install -r requirements.txt
          pip3 install pyinstaller sysv-ipc geoip2
          ./build.sh && mv -f *.tar.gz *.sha512sum bin
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git pull && git add bin && git commit -m "update debian binaries" && git push
  
  centos7-container-build-job:
    name: Build for CentOS 7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      # get git-2.18 from softwarecollections since git-1.8 from base repo is too old for gh-actions
      - name: Install git-2.18
        run: |
          yum install -y centos-release-scl && yum install -y rh-git218
          cp -v -rf /opt/rh/httpd24/root/* /opt/rh/rh-git218/root/* / || true
          git --version; ls -la /usr/bin/git
      - uses: actions/checkout@v2
      - name: Run yum, venv, pip, build and git commit
        run: |
          yum install -y gcc python3-devel python3-pip python3-virtualenv
          yum install -y https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/u/ucl-1.03-24.el7.x86_64.rpm
          yum install -y https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/u/upx-3.96-9.el7.x86_64.rpm
          python3 -m venv venv && . venv/bin/activate
          pip3 install --upgrade pip wheel setuptools
          pip3 install -r requirements.txt
          pip3 install pyinstaller sysv-ipc geoip2
          ./build.sh && mv -f *.tar.gz *.sha512sum bin
          id; git --version; ls -la /usr/bin/git; pwd; ls -la
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git pull && git add bin && git commit -m "update centos binary" && git push
